export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

export default {
    // Auth actions
    AUTH_USER: 'AUTH_USER',
    AUTH_ERROR: 'AUTH_ERROR',

    // Garden actions
    GARDEN_FETCH: 'GARDEN_FETCH',
    GARDEN_FETCH_ALL: 'GARDEN_FETCH_ALL',
    GARDEN_NEW: 'GARDEN_NEW',
    GARDEN_DELETE: 'GARDEN_DELETE',
    GARDEN_EDIT: 'GARDEN_EDIT',
    PLANT_NEW: 'PLANT_NEW',
    PLANT_TRANSPLANT: 'PLANT_TRANSPLANT',
    PLANT_REMOVE: 'PLANT_REMOVE',
    PLANT_DELETE: 'PLANT_DELETE',
    PLANT_CONFIRM_NEW: 'PLANT_CONFIRM_NEW'
}